/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.TinTuc;
import javax.swing.ImageIcon;
import controller.ControllerTinTuc;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.ModelTinTuc;
import render.DanhMucComboboxModel;

/**
 *
 * @author vuongluis
 */
public class demo extends javax.swing.JFrame {

    private ControllerTinTuc controller;
    private String imageAvatar = "logo.apple.png";
    private String chiTiet = " ";
    private ModelTinTuc mNew;
    /**
     * Creates new form demo
     */
    public demo() {
        initComponents();
        ImageIcon image = new ImageIcon(getClass().getResource("/images/icon.png"));
        this.setIconImage(image.getImage());
        this.setTitle("NewsApp"); /** a short time **/
        cbDanhMuc.setModel(new DanhMucComboboxModel());
        controller = new ControllerTinTuc(tbMain);
        controller.loadTable();
        Image imagex =new ImageIcon("files/logo.apple.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        lbAvatar.setIcon(new ImageIcon(imagex));
        mNew = new ModelTinTuc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        First = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        CenterX = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        CenterY = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        Left = new javax.swing.JPanel();
        Leftxa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfTenTin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfMoTa = new javax.swing.JTextArea();
        Upload = new javax.swing.JButton();
        tfNgayDang = new javax.swing.JSpinner();
        cbDanhMuc = new javax.swing.JComboBox();
        lbAvatar = new javax.swing.JLabel();
        Leftxb = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfChiTiet = new javax.swing.JTextArea();
        Leftxc = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        Right = new javax.swing.JPanel();
        RightXA = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        ButtonControl = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        RightXB = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();
        Last = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        First.setBackground(new java.awt.Color(214, 217, 224));
        First.setLayout(new java.awt.BorderLayout());

        jButton2.setBackground(new java.awt.Color(234, 237, 244));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qlnews.png"))); // NOI18N
        jButton2.setText("<html>\n<p>Quản Lý<br>Tin Tức</p>\n</html>");
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        First.add(jButton2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(First, java.awt.BorderLayout.PAGE_START);

        Center.setBackground(new java.awt.Color(214, 217, 224));
        Center.setLayout(new java.awt.BorderLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setText("Quản Lý Tin Tức");
        CenterX.add(title);

        Center.add(CenterX, java.awt.BorderLayout.PAGE_START);

        CenterY.setLayout(new java.awt.GridLayout(1, 2));

        Left.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Form chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(62, 164, 87))); // NOI18N
        Left.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID tin:");

        jLabel2.setText("Tên tin:");

        jLabel3.setText("Mô tả:");

        jLabel5.setText("Ngày đăng:");

        jLabel6.setText("Danh mục:");

        jLabel4.setText("Hình ảnh:");

        tfID.setEditable(false);
        tfID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tfTenTin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tfMoTa.setColumns(20);
        tfMoTa.setLineWrap(true);
        tfMoTa.setRows(5);
        tfMoTa.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tfMoTa);

        Upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        Upload.setText("Upload");
        Upload.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });

        tfNgayDang.setModel(new javax.swing.SpinnerDateModel());
        tfNgayDang.setEditor(new javax.swing.JSpinner.DateEditor(tfNgayDang, "dd/MM/yyyy"));

        cbDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbDanhMuc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tin Thế Giới" }));

        javax.swing.GroupLayout LeftxaLayout = new javax.swing.GroupLayout(Leftxa);
        Leftxa.setLayout(LeftxaLayout);
        LeftxaLayout.setHorizontalGroup(
            LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftxaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftxaLayout.createSequentialGroup()
                        .addComponent(tfID, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(203, 203, 203))
                    .addGroup(LeftxaLayout.createSequentialGroup()
                        .addComponent(tfTenTin)
                        .addGap(10, 10, 10))
                    .addGroup(LeftxaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(10, 10, 10))
                    .addGroup(LeftxaLayout.createSequentialGroup()
                        .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNgayDang)
                            .addComponent(cbDanhMuc, 0, 152, Short.MAX_VALUE)
                            .addComponent(Upload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        LeftxaLayout.setVerticalGroup(
            LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftxaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTenTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftxaLayout.createSequentialGroup()
                        .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeftxaLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4))
                            .addGroup(LeftxaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNgayDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(LeftxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(LeftxaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Left.add(Leftxa, java.awt.BorderLayout.PAGE_START);

        jLabel7.setText("Chi tiết:");

        tfChiTiet.setColumns(20);
        tfChiTiet.setLineWrap(true);
        tfChiTiet.setRows(5);
        tfChiTiet.setWrapStyleWord(true);
        jScrollPane2.setViewportView(tfChiTiet);

        javax.swing.GroupLayout LeftxbLayout = new javax.swing.GroupLayout(Leftxb);
        Leftxb.setLayout(LeftxbLayout);
        LeftxbLayout.setHorizontalGroup(
            LeftxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftxbLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
        LeftxbLayout.setVerticalGroup(
            LeftxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftxbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Left.add(Leftxb, java.awt.BorderLayout.CENTER);

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        Leftxc.add(btnThem);

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btnSua.setText("Sữa");
        btnSua.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        Leftxc.add(btnSua);

        btnNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });
        Leftxc.add(btnNhapLai);

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hr.gif"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        Leftxc.add(btnXoa);

        Left.add(Leftxc, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setLeftComponent(Left);

        Right.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(62, 164, 87))); // NOI18N
        Right.setLayout(new java.awt.BorderLayout());

        RightXA.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(214, 217, 223)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel8.setText("ID:");

        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setText("Tên:");

        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ButtonControl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        jButton6.setText("Tìm kiếm");
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ButtonControl.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hr.gif"))); // NOI18N
        jButton7.setText("Xóa tìm kiếm");
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ButtonControl.add(jButton7);

        javax.swing.GroupLayout RightXALayout = new javax.swing.GroupLayout(RightXA);
        RightXA.setLayout(RightXALayout);
        RightXALayout.setHorizontalGroup(
            RightXALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightXALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(47, 47, 47)
                .addComponent(jTextField3)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4)
                .addGap(45, 45, 45))
            .addComponent(ButtonControl, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        RightXALayout.setVerticalGroup(
            RightXALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightXALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RightXALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Right.add(RightXA, java.awt.BorderLayout.PAGE_START);

        RightXB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 10, new java.awt.Color(214, 217, 223)));

        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMainMousePressed(evt);
            }
        });
        tbMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbMainKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMainKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbMain);

        javax.swing.GroupLayout RightXBLayout = new javax.swing.GroupLayout(RightXB);
        RightXB.setLayout(RightXBLayout);
        RightXBLayout.setHorizontalGroup(
            RightXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        RightXBLayout.setVerticalGroup(
            RightXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        Right.add(RightXB, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(Right);

        CenterY.add(jSplitPane1);

        Center.add(CenterY, java.awt.BorderLayout.CENTER);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        Last.setBackground(new java.awt.Color(214, 217, 224));
        Last.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Copyright by © VinaENTER - Code By VinaENTER");
        Last.add(jLabel10);

        getContentPane().add(Last, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMainMousePressed
        setForm();
    }//GEN-LAST:event_tbMainMousePressed

    private void tbMainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMainKeyPressed
        setForm();
    }//GEN-LAST:event_tbMainKeyPressed

    private void tbMainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMainKeyReleased
        setForm();
    }//GEN-LAST:event_tbMainKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(tfTenTin.getText().isEmpty()){
            JOptionPane.showMessageDialog(new demo(), "Nhập vào tên tin tức","Thông báo",JOptionPane.WARNING_MESSAGE);
            return ;
        }
        String tenTinTuc = tfTenTin.getText();
        String moTa = tfMoTa.getText();
        String tenDanhMuc = new DanhMucComboboxModel().getElementAt(cbDanhMuc.getSelectedIndex()).getTenDanhMuc();
        String hinhAnh = imageAvatar;
        String chiTietTin = tfChiTiet.getText();
        if(controller.addItem(new TinTuc(tenTinTuc,tenDanhMuc,hinhAnh,moTa),chiTietTin)>0){
            JOptionPane.showMessageDialog(rootPane,"Thêm thành công","",JOptionPane.INFORMATION_MESSAGE);
            resetForm();
        }else{
            JOptionPane.showMessageDialog(rootPane,"Thêm thất bại","",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed
        JFileChooser chooser = new JFileChooser("C:\\Users\\vuongluis\\Pictures\\");
        int result = chooser.showDialog(null, "Upload Ảnh");
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                File file = chooser.getSelectedFile();
                // lấy tên hình ảnh
                    String fileName = file.getName();
                    imageAvatar = fileName;
                    // validate or filter file extension
                    // file.getAbsoluteFile();
                    Path source = Paths.get( file.getAbsolutePath());
                    Path target = Paths.get("files/"+fileName);
                    /** If the picture is exist so this picture replace that picture. **/
                    Files.copy(source,target ,StandardCopyOption.REPLACE_EXISTING );
                    Image image =new ImageIcon("files/"+fileName).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                    lbAvatar.setIcon(new ImageIcon(image));
            } catch (IOException ex) {
                Logger.getLogger(demo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_UploadActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tbMain.getSelectedRow();
        if(row > 0){
            int id = Integer.parseInt(tfID.getText());
            if(controller.delItem(id,row)>0){
                JOptionPane.showMessageDialog(rootPane,"Xóa thành công","",JOptionPane.INFORMATION_MESSAGE);
                resetForm();
            }else{
                JOptionPane.showMessageDialog(rootPane,"Xóa thất bại","",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Chọn hàng để xóa","",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        resetForm();
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tbMain.getSelectedRow();
        if(row >= 0){
            String tenTinTuc = tfTenTin.getText();
            String moTa = tfMoTa.getText();
            String tenDanhMuc = new DanhMucComboboxModel().getElementAt(cbDanhMuc.getSelectedIndex()).getTenDanhMuc();
            String hinhAnh = imageAvatar;
            String chiTietTin = tfChiTiet.getText();
            if(controller.editItem(new TinTuc(tenTinTuc,tenDanhMuc,hinhAnh,moTa),chiTietTin,row)>0){
                JOptionPane.showMessageDialog(rootPane,"Sữa thành công","",JOptionPane.INFORMATION_MESSAGE);
                resetForm();
            }else{
                JOptionPane.showMessageDialog(rootPane,"Sữa thất bại","",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Chọn hàng để sữa","",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonControl;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel CenterX;
    private javax.swing.JPanel CenterY;
    private javax.swing.JPanel First;
    private javax.swing.JPanel Last;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Leftxa;
    private javax.swing.JPanel Leftxb;
    private javax.swing.JPanel Leftxc;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel RightXA;
    private javax.swing.JPanel RightXB;
    private javax.swing.JButton Upload;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cbDanhMuc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JTable tbMain;
    private javax.swing.JTextArea tfChiTiet;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextArea tfMoTa;
    private javax.swing.JSpinner tfNgayDang;
    private javax.swing.JTextField tfTenTin;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void setForm() {
        int row=tbMain.getSelectedRow();
        int id=(Integer)controller.getValueAt(row, 0);
        String tenTinTuc=controller.getValueAt(row, 1).toString();
        // String danhMuc=controller.getValueAt(row, 2).toString();
        String moTa =controller.getValueAt(row, 3).toString();
        String ngayDang=mNew.getItem(id).getNgayDang();
        if(!mNew.getItem(id).getChiTiet().isEmpty()){
            chiTiet = mNew.getItem(id).getChiTiet();
        }
        /*------- Convert date sql to date time and view in user ----------*/
        String xdate[] = ngayDang.split("-");        
        Date date = new Date(Integer.parseInt(xdate[0])-1900, Integer.parseInt(xdate[1])-1, Integer.parseInt(xdate[2]));
        tfID.setText(id+"");
        tfTenTin.setText(tenTinTuc+"");
        tfMoTa.setText(moTa+"");
        tfNgayDang.setValue(date);
        tfChiTiet.setText(chiTiet);
    }

    private void resetForm() {
        tfID.setText(""); 
        tfTenTin.setText("");
        tfMoTa.setText("");
        tfNgayDang.setValue(new Date());
        cbDanhMuc.setSelectedIndex(0);
        Image imagex =new ImageIcon("files/logo.apple.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        lbAvatar.setIcon(new ImageIcon(imagex));
        tfChiTiet.setText("");
    }
}
